export const REQUEST_PRIVILEGES = 'REQUEST_PRIVILEGES';

export const RECEIVE_PRIVILEGES = 'RECEIVE_PRIVILEGES';

export const REQUEST_PRIVILEGE = 'REQUEST_PRIVILEGE';

export const RECEIVE_PRIVILEGE = 'RECEIVE_PRIVILEGE';

export const REQUEST_CREATE_PRIVILEGE = 'REQUEST_CREATE_PRIVILEGE';

export const RECEIVE_CREATE_PRIVILEGE = 'RECEIVE_CREATE_PRIVILEGE';

export const FETCH_ERROR = 'FETCH_ERROR';

export const UPDATE_NEW_PRIVILEGE_NAME = 'UPDATE_NEW_PRIVILEGE_NAME';

export const UPDATE_NEW_PRIVILEGE_STATUS = 'UPDATE_NEW_PRIVILEGE_STATUS';

export const RECEIVE_NEW_PRIVILEGE = 'RECEIVE_NEW_PRIVILEGE';

export const UPDATE_PRIVILEGE_NAME = 'UPDATE_PRIVILEGE_NAME';

export const REQUEST_SAVE_PRIVILEGE = 'REQUEST_SAVE_PRIVILEGE';

export const TOGGLE_PRIVILEGE_STATUS = 'TOGGLE_PRIVILEGE_STATUS';

export const REQUEST_DELETE_PRIVILEGE = 'REQUEST_DELETE_PRIVILEGE';

export const RECEIVE_PRIVILEGE_DELETED = 'RECEIVE_PRIVILEGE_DELETED';

export const SET_UPDATE_MESSAGE_VISIBILITY = 'SET_UPDATE_MESSAGE_VISIBILITY';

export const RECEIVE_UPDATED_PRIVILEGE = 'RECEIVE_UPDATED_PRIVILEGE';
