export const REQUEST_PRIVILEGES = 'REQUEST_PRIVILEGES';

export const RECEIVE_PRIVILEGES = 'RECEIVE_PRIVILEGES';

export const RECEIVE_POTENTIAL_GROUP_PRIVILEGES = 'RECEIVE_POTENTIAL_GROUP_PRIVILEGES';

export const REQUEST_POTENTIAL_GROUP_PRIVILEGES = 'REQUEST_POTENTIAL_GROUP_PRIVILEGES';

export const REQUEST_PRIVILEGES_FOR_ASSIGNMENT = 'REQUEST_PRIVILEGES_FOR_ASSIGNMENT';

export const RECEIVE_PRIVILEGES_FOR_ASSIGNMENT = 'RECEIVE_PRIVILEGES_FOR_ASSIGNMENT';

export const REQUEST_PRIVILEGE = 'REQUEST_PRIVILEGE';

export const RECEIVE_PRIVILEGE = 'RECEIVE_PRIVILEGE';

export const REQUEST_CREATE_PRIVILEGE = 'REQUEST_CREATE_PRIVILEGE';

export const RECEIVE_CREATE_PRIVILEGE = 'RECEIVE_CREATE_PRIVILEGE';

export const REQUEST_CREATE_PERMISSION = 'REQUEST_CREATE_PERMISSION';

export const RECEIVE_CREATE_PERMISSION = 'RECEIVE_CREATE_PERMISSION';

export const SET_PERMISSION_MESSAGE_VISIBILITY = 'SET_PERMISSION_MESSAGE_VISIBILITY';

export const REQUEST_DELETE_PERMISSION = 'REQUEST_DELETE_PERMISSION';

export const RECEIVE_DELETE_PERMISSION = 'RECEIVE_DELETE_PERMISSION';

export const FETCH_ERROR = 'FETCH_ERROR';

export const UPDATE_NEW_PRIVILEGE_NAME = 'UPDATE_NEW_PRIVILEGE_NAME';

export const UPDATE_NEW_PRIVILEGE_STATUS = 'UPDATE_NEW_PRIVILEGE_STATUS';

export const UPDATE_SELECTED_USER = 'UPDATE_SELECTED_USER';

export const RECEIVE_NEW_PRIVILEGE = 'RECEIVE_NEW_PRIVILEGE';

export const UPDATE_PRIVILEGE_NAME = 'UPDATE_PRIVILEGE_NAME';

export const REQUEST_SAVE_PRIVILEGE = 'REQUEST_SAVE_PRIVILEGE';

export const TOGGLE_PRIVILEGE_STATUS = 'TOGGLE_PRIVILEGE_STATUS';

export const REQUEST_DELETE_PRIVILEGE = 'REQUEST_DELETE_PRIVILEGE';

export const RECEIVE_PRIVILEGE_DELETED = 'RECEIVE_PRIVILEGE_DELETED';

export const SET_UPDATE_MESSAGE_VISIBILITY = 'SET_UPDATE_MESSAGE_VISIBILITY';

export const RECEIVE_UPDATED_PRIVILEGE = 'RECEIVE_UPDATED_PRIVILEGE';

export const REQUEST_PRIVILEGES_FOR_USER = 'REQUEST_PRIVILEGES_FOR_USER';

export const RECEIVE_PRIVILEGES_FOR_USER = 'RECEIVE_PRIVILEGES_FOR_USER';

export const REQUEST_PRIVILEGES_FOR_GROUP = 'REQUEST_PRIVILEGES_FOR_GROUP';

export const RECEIVE_PRIVILEGES_FOR_GROUP = 'RECEIVE_PRIVILEGES_FOR_GROUP';

export const REQUEST_MEMBERS_FOR_GROUP = 'REQUEST_MEMBERS_FOR_GROUP';

export const RECEIVE_MEMBERS_FOR_GROUP = 'RECEIVE_MEMBERS_FOR_GROUP';

export const REQUEST_USERS = 'REQUEST_USERS';

export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_GROUPS = 'REQUEST_GROUPS';

export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';

export const UPDATE_NEW_GROUP_NAME = 'UPDATE_NEW_GROUP_NAME';

export const REQUEST_GROUP = 'REQUEST_GROUP';

export const RECEIVE_GROUP = 'RECEIVE_GROUP';

export const REQUEST_CREATE_GROUP = 'REQUEST_CREATE_GROUP';

export const RECEIVE_NEW_GROUP = 'RECEIVE_NEW_GROUP';

export const UPDATE_GROUP_NAME = 'UPDATE_GROUP_NAME';

export const REQUEST_SAVE_GROUP = 'REQUEST_SAVE_GROUP';

export const RECEIVE_UPDATED_GROUP = 'RECEIVE_UPDATED_GROUP';

export const TOGGLE_GROUP_STATUS = 'TOGGLE_GROUP_STATUS';

export const REQUEST_CREATE_GROUP_PERMISSION = 'REQUEST_CREATE_GROUP_PERMISSION';

export const RECEIVE_CREATE_GROUP_PERMISSION = 'RECEIVE_CREATE_GROUP_PERMISSION';

export const REQUEST_CREATE_INDIVIDUAL_MEMBER = 'REQUEST_CREATE_INDIVIDUAL_MEMBER';

export const RECEIVE_CREATE_INDIVIDUAL_MEMBER = 'RECEIVE_CREATE_INDIVIDUAL_MEMBER';

export const REQUEST_DELETE_GROUP_PERMISSION = 'REQUEST_DELETE_GROUP_PERMISSION';

export const RECEIVE_DELETE_GROUP_PERMISSION = 'RECEIVE_DELETE_GROUP_PERMISSION';

export const REQUEST_DELETE_MEMBER = 'REQUEST_DELETE_MEMBER';

export const RECEIVE_DELETE_MEMBER = 'RECEIVE_DELETE_MEMBER';
