export const REQUEST_PRIVILEGES = 'REQUEST_PRIVILEGES';

export const RECEIVE_PRIVILEGES = 'RECEIVE_PRIVILEGES';

export const REQUEST_PRIVILEGE = 'REQUEST_PRIVILEGE';

export const RECEIVE_PRIVILEGE = 'RECEIVE_PRIVILEGE';

export const FETCH_ERROR = 'FETCH_ERROR';
